#!/usr/bin/env bash
# Configures Nginx to listen on port 80 and restarts the service.
sed -i 's/listen 8080 default_server;/listen 80 default_server;/' /etc/nginx/sites-enabled/default
service nginx restart