#!/usr/bin/env bash
# Installs Nginx and configures its homepage with the required content.
apt-get update
apt-get install -y nginx
printf '%s\n' 'Holberton School for the win!' > /var/www/html/index.html
service nginx restart
