#!/usr/bin/env bash
# Installs Nginx and configures a permanent redirect for /redirect_me.
apt-get update
apt-get install -y nginx
printf '%s\n' 'Holberton School for the win!' > /var/www/html/index.html
sed -i '/server_name _;/a \        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
nginx -t
service nginx restart
